export const ERROR_TYPES = {
  FETCH_QUESTIONS_ERROR: 'FETCH_QUESTIONS_ERROR',
  USER_HISTORY_ERROR: 'USER_HISTORY_ERROR',
  SESSION_CREATION_ERROR: 'SESSION_CREATION_ERROR',
  RESPONSE_RECORDING_ERROR: 'RESPONSE_RECORDING_ERROR',
  INSUFFICIENT_QUESTIONS_ERROR: 'INSUFFICIENT_QUESTIONS_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR'
}